Repository LizardByte/Sunshine, pull requests merged in 2024-05, with the labels that each got.

#2335 fix(file_handler): avoid writing extra newline character
  src/file_handler.cpp
  tests/unit/test_file_handler.cpp
Labels: pr:planned

#2429 AppImage: add needed VA-API libraries (Intel & AMD)
  .github/workflows/CI.yml
Labels: pr:planned

#2454 New Crowdin updates
  src_assets/common/assets/web/public/assets/locale/de.json
  src_assets/common/assets/web/public/assets/locale/en_GB.json
  src_assets/common/assets/web/public/assets/locale/en_US.json
  src_assets/common/assets/web/public/assets/locale/es.json
  src_assets/common/assets/web/public/assets/locale/fr.json
  src_assets/common/assets/web/public/assets/locale/it.json
  src_assets/common/assets/web/public/assets/locale/ja.json
  src_assets/common/assets/web/public/assets/locale/pt.json
  src_assets/common/assets/web/public/assets/locale/ru.json
  src_assets/common/assets/web/public/assets/locale/sv.json
  src_assets/common/assets/web/public/assets/locale/zh.json
Labels: crowdin, l10n

#2323 build(win): use UCRT64 environment instead of MinGW64.
  .github/workflows/CI.yml
  docs/source/building/windows.rst
  src/config.cpp
  src/main.cpp
  src_assets/windows/misc/migration/migrate-config.bat
Labels: pr:under condideration

#2562 New Crowdin updates
  src_assets/common/assets/web/public/assets/locale/de.json
  src_assets/common/assets/web/public/assets/locale/en_GB.json
  src_assets/common/assets/web/public/assets/locale/en_US.json
  src_assets/common/assets/web/public/assets/locale/es.json
  src_assets/common/assets/web/public/assets/locale/fr.json
  src_assets/common/assets/web/public/assets/locale/it.json
  src_assets/common/assets/web/public/assets/locale/ja.json
  src_assets/common/assets/web/public/assets/locale/pt.json
  src_assets/common/assets/web/public/assets/locale/ru.json
  src_assets/common/assets/web/public/assets/locale/sv.json
  src_assets/common/assets/web/public/assets/locale/zh.json
Labels: crowdin, l10n

#2584 New Crowdin updates
  src_assets/common/assets/web/public/assets/locale/pt.json
Labels: crowdin, l10n
